# Generated by Django 2.2.3 on 2021-11-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_article_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='avatar',
        ),
    ]
