# Generated by Django 2.2.3 on 2021-11-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_article_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='category_id',
        ),
    ]
