# Generated by Django 2.2.3 on 2021-11-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211110_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='context',
            new_name='content',
        ),
    ]
